apiVersion: v1
kind: Service
metadata:
  name: {{ include "intelligence.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "intelligence.fullname" . }}
    app.kubernetes.io/component: "frontend"
  ports:
    - port: 8080
      targetPort: 8080
  type: {{ .Values.service.type }}