apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification.fullname" . }}
  namespace: {{ .Values.namespace.name }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_SCHEMA_REGISTRY_URL: {{ .Values.kafka.schemaRegistryUrl | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT | quote }}
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT | quote }}
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_LOGS_ENDPOINT | quote }}
  OTEL_TRACES_SAMPLER_ARG: {{ .Values.config.OTEL_TRACES_SAMPLER_ARG | quote }}

