{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "notification.labels" . | nindent 4 }}
{{- end }}