/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.agilesolutions.common.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Published when a notebook is created. */
@org.apache.avro.specific.AvroGenerated
public class NotebookCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 284591043633724000L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotebookCreated\",\"namespace\":\"com.agilesolutions.common.events\",\"doc\":\"Published when a notebook is created.\",\"fields\":[{\"name\":\"eventId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier of this event.\"},{\"name\":\"eventType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"default\":\"NotebookCreated\"},{\"name\":\"eventVersion\",\"type\":\"int\",\"default\":1},{\"name\":\"occurredAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UTC timestamp when the event occurred.\"},{\"name\":\"notebookId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"title\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NotebookCreated> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NotebookCreated> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NotebookCreated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NotebookCreated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NotebookCreated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NotebookCreated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NotebookCreated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NotebookCreated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NotebookCreated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier of this event. */
  private java.lang.String eventId;
  private java.lang.String eventType;
  private int eventVersion;
  /** UTC timestamp when the event occurred. */
  private java.lang.String occurredAt;
  private java.lang.String notebookId;
  private java.lang.String title;
  private java.lang.String description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NotebookCreated() {}

  /**
   * All-args constructor.
   * @param eventId Unique identifier of this event.
   * @param eventType The new value for eventType
   * @param eventVersion The new value for eventVersion
   * @param occurredAt UTC timestamp when the event occurred.
   * @param notebookId The new value for notebookId
   * @param title The new value for title
   * @param description The new value for description
   */
  public NotebookCreated(java.lang.String eventId, java.lang.String eventType, java.lang.Integer eventVersion, java.lang.String occurredAt, java.lang.String notebookId, java.lang.String title, java.lang.String description) {
    this.eventId = eventId;
    this.eventType = eventType;
    this.eventVersion = eventVersion;
    this.occurredAt = occurredAt;
    this.notebookId = notebookId;
    this.title = title;
    this.description = description;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return eventType;
    case 2: return eventVersion;
    case 3: return occurredAt;
    case 4: return notebookId;
    case 5: return title;
    case 6: return description;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = value$ != null ? value$.toString() : null; break;
    case 1: eventType = value$ != null ? value$.toString() : null; break;
    case 2: eventVersion = (java.lang.Integer)value$; break;
    case 3: occurredAt = value$ != null ? value$.toString() : null; break;
    case 4: notebookId = value$ != null ? value$.toString() : null; break;
    case 5: title = value$ != null ? value$.toString() : null; break;
    case 6: description = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return Unique identifier of this event.
   */
  public java.lang.String getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * Unique identifier of this event.
   * @param value the value to set.
   */
  public void setEventId(java.lang.String value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.String getEventType() {
    return eventType;
  }


  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.String value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'eventVersion' field.
   * @return The value of the 'eventVersion' field.
   */
  public int getEventVersion() {
    return eventVersion;
  }


  /**
   * Sets the value of the 'eventVersion' field.
   * @param value the value to set.
   */
  public void setEventVersion(int value) {
    this.eventVersion = value;
  }

  /**
   * Gets the value of the 'occurredAt' field.
   * @return UTC timestamp when the event occurred.
   */
  public java.lang.String getOccurredAt() {
    return occurredAt;
  }


  /**
   * Sets the value of the 'occurredAt' field.
   * UTC timestamp when the event occurred.
   * @param value the value to set.
   */
  public void setOccurredAt(java.lang.String value) {
    this.occurredAt = value;
  }

  /**
   * Gets the value of the 'notebookId' field.
   * @return The value of the 'notebookId' field.
   */
  public java.lang.String getNotebookId() {
    return notebookId;
  }


  /**
   * Sets the value of the 'notebookId' field.
   * @param value the value to set.
   */
  public void setNotebookId(java.lang.String value) {
    this.notebookId = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.String getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.String value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Creates a new NotebookCreated RecordBuilder.
   * @return A new NotebookCreated RecordBuilder
   */
  public static com.agilesolutions.common.events.NotebookCreated.Builder newBuilder() {
    return new com.agilesolutions.common.events.NotebookCreated.Builder();
  }

  /**
   * Creates a new NotebookCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NotebookCreated RecordBuilder
   */
  public static com.agilesolutions.common.events.NotebookCreated.Builder newBuilder(com.agilesolutions.common.events.NotebookCreated.Builder other) {
    if (other == null) {
      return new com.agilesolutions.common.events.NotebookCreated.Builder();
    } else {
      return new com.agilesolutions.common.events.NotebookCreated.Builder(other);
    }
  }

  /**
   * Creates a new NotebookCreated RecordBuilder by copying an existing NotebookCreated instance.
   * @param other The existing instance to copy.
   * @return A new NotebookCreated RecordBuilder
   */
  public static com.agilesolutions.common.events.NotebookCreated.Builder newBuilder(com.agilesolutions.common.events.NotebookCreated other) {
    if (other == null) {
      return new com.agilesolutions.common.events.NotebookCreated.Builder();
    } else {
      return new com.agilesolutions.common.events.NotebookCreated.Builder(other);
    }
  }

  /**
   * RecordBuilder for NotebookCreated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotebookCreated>
    implements org.apache.avro.data.RecordBuilder<NotebookCreated> {

    /** Unique identifier of this event. */
    private java.lang.String eventId;
    private java.lang.String eventType;
    private int eventVersion;
    /** UTC timestamp when the event occurred. */
    private java.lang.String occurredAt;
    private java.lang.String notebookId;
    private java.lang.String title;
    private java.lang.String description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.agilesolutions.common.events.NotebookCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.eventVersion)) {
        this.eventVersion = data().deepCopy(fields()[2].schema(), other.eventVersion);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[3].schema(), other.occurredAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.notebookId)) {
        this.notebookId = data().deepCopy(fields()[4].schema(), other.notebookId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.title)) {
        this.title = data().deepCopy(fields()[5].schema(), other.title);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.description)) {
        this.description = data().deepCopy(fields()[6].schema(), other.description);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing NotebookCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(com.agilesolutions.common.events.NotebookCreated other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventType)) {
        this.eventType = data().deepCopy(fields()[1].schema(), other.eventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventVersion)) {
        this.eventVersion = data().deepCopy(fields()[2].schema(), other.eventVersion);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.occurredAt)) {
        this.occurredAt = data().deepCopy(fields()[3].schema(), other.occurredAt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.notebookId)) {
        this.notebookId = data().deepCopy(fields()[4].schema(), other.notebookId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.title)) {
        this.title = data().deepCopy(fields()[5].schema(), other.title);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.description)) {
        this.description = data().deepCopy(fields()[6].schema(), other.description);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * Unique identifier of this event.
      * @return The value.
      */
    public java.lang.String getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * Unique identifier of this event.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setEventId(java.lang.String value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * Unique identifier of this event.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * Unique identifier of this event.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventType' field.
      * @return The value.
      */
    public java.lang.String getEventType() {
      return eventType;
    }


    /**
      * Sets the value of the 'eventType' field.
      * @param value The value of 'eventType'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setEventType(java.lang.String value) {
      validate(fields()[1], value);
      this.eventType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventType' field has been set.
      * @return True if the 'eventType' field has been set, false otherwise.
      */
    public boolean hasEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventType' field.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventVersion' field.
      * @return The value.
      */
    public int getEventVersion() {
      return eventVersion;
    }


    /**
      * Sets the value of the 'eventVersion' field.
      * @param value The value of 'eventVersion'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setEventVersion(int value) {
      validate(fields()[2], value);
      this.eventVersion = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventVersion' field has been set.
      * @return True if the 'eventVersion' field has been set, false otherwise.
      */
    public boolean hasEventVersion() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventVersion' field.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearEventVersion() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'occurredAt' field.
      * UTC timestamp when the event occurred.
      * @return The value.
      */
    public java.lang.String getOccurredAt() {
      return occurredAt;
    }


    /**
      * Sets the value of the 'occurredAt' field.
      * UTC timestamp when the event occurred.
      * @param value The value of 'occurredAt'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setOccurredAt(java.lang.String value) {
      validate(fields()[3], value);
      this.occurredAt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'occurredAt' field has been set.
      * UTC timestamp when the event occurred.
      * @return True if the 'occurredAt' field has been set, false otherwise.
      */
    public boolean hasOccurredAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'occurredAt' field.
      * UTC timestamp when the event occurred.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearOccurredAt() {
      occurredAt = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'notebookId' field.
      * @return The value.
      */
    public java.lang.String getNotebookId() {
      return notebookId;
    }


    /**
      * Sets the value of the 'notebookId' field.
      * @param value The value of 'notebookId'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setNotebookId(java.lang.String value) {
      validate(fields()[4], value);
      this.notebookId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'notebookId' field has been set.
      * @return True if the 'notebookId' field has been set, false otherwise.
      */
    public boolean hasNotebookId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'notebookId' field.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearNotebookId() {
      notebookId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.String getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setTitle(java.lang.String value) {
      validate(fields()[5], value);
      this.title = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearTitle() {
      title = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder setDescription(java.lang.String value) {
      validate(fields()[6], value);
      this.description = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.agilesolutions.common.events.NotebookCreated.Builder clearDescription() {
      description = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NotebookCreated build() {
      try {
        NotebookCreated record = new NotebookCreated();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.String) defaultValue(fields()[0]);
        record.eventType = fieldSetFlags()[1] ? this.eventType : (java.lang.String) defaultValue(fields()[1]);
        record.eventVersion = fieldSetFlags()[2] ? this.eventVersion : (java.lang.Integer) defaultValue(fields()[2]);
        record.occurredAt = fieldSetFlags()[3] ? this.occurredAt : (java.lang.String) defaultValue(fields()[3]);
        record.notebookId = fieldSetFlags()[4] ? this.notebookId : (java.lang.String) defaultValue(fields()[4]);
        record.title = fieldSetFlags()[5] ? this.title : (java.lang.String) defaultValue(fields()[5]);
        record.description = fieldSetFlags()[6] ? this.description : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NotebookCreated>
    WRITER$ = (org.apache.avro.io.DatumWriter<NotebookCreated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NotebookCreated>
    READER$ = (org.apache.avro.io.DatumReader<NotebookCreated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.eventType);

    out.writeInt(this.eventVersion);

    out.writeString(this.occurredAt);

    out.writeString(this.notebookId);

    out.writeString(this.title);

    if (this.description == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.description);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString();

      this.eventType = in.readString();

      this.eventVersion = in.readInt();

      this.occurredAt = in.readString();

      this.notebookId = in.readString();

      this.title = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.description = null;
      } else {
        this.description = in.readString();
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString();
          break;

        case 1:
          this.eventType = in.readString();
          break;

        case 2:
          this.eventVersion = in.readInt();
          break;

        case 3:
          this.occurredAt = in.readString();
          break;

        case 4:
          this.notebookId = in.readString();
          break;

        case 5:
          this.title = in.readString();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.description = null;
          } else {
            this.description = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










