spring:
  application:
    name: audit-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://notebook-postgresql.database.svc.cluster.local:5432/notebook}
    username: ${SPRING_DATASOURCE_USERNAME:notebook}
    password: ${SPRING_DATASOURCE_PASSWORD:notebook}
    driver-class-name: org.postgresql.Driver


  flyway:
    enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.kafka-dev.svc.cluster.local:9093}

    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL:http://kafka.kafka-dev.svc.cluster.local:8081}
        specific.avro.reader: true
    listener:
      ack-mode: record

app:
  kafka:
    topics:
      notebook-events: notebook.events

logging:
  level:
    com.agilesolutions.audit: INFO
    org.apache.kafka: WARN